spring:
  datasource:
    username: root
    password: sbzl2004
    url: jdbc:mysql://localhost:3306/supermarket
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sup.pojo